---
title: "589project"
author: "Rui Mao, Zheng Zhang, Zerui Zhang"
date: "2024-04-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, fig.width=8, fig.height=6, fig.align = 'center')
```

## Load Package
```{r warning=FALSE}
library(sf)
library(spatstat)
library(sp)
library(maptools)
library(dplyr)
library(readr)
library(ggplot2)
library(lubridate)
```

## Load Full Data
```{r run-once, echo=FALSE}
bird_bc <- read_csv('bc_bird.csv') %>%
  # filter(stateProvince == "British Columbia") %>%
  select_if(~ !all(is.na(.))) %>%
  filter(!is.na(decimalLongitude) & !is.na(decimalLatitude))
# write.csv(bird_bc, "bc_bird.csv", row.names = FALSE)
```

## Filter data 
```{r run-once, echo=FALSE}
bird_data <- bird_bc %>%
  mutate(eventDate = ymd(eventDate)) %>%
  filter(year(eventDate) > 2015) %>%
  select(species, eventDate, individualCount, iucnRedListCategory, decimalLatitude, decimalLongitude)
write.csv(bird_data, "bird_data.csv", row.names = FALSE)
```

## Load Data
```{r}
bird_data <- read_csv('bird_data.csv')
load('BC_Covariates.Rda')
window = DATA$Window
```

```{r}
bird_sf <- st_as_sf(bird_data, coords = c("decimalLongitude", "decimalLatitude"), crs = 4326)
bc_albers_crs_string <- "+proj=aea +lat_0=45 +lon_0=-126 +lat_1=50 +lat_2=58.5 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs"
bird_albers <- st_transform(bird_sf, crs = bc_albers_crs_string)
```

## Distribution
```{r}
ggplot(data = bird_albers) +
  geom_sf(aes(color = species), size = 0.6) +
  labs(title = "Distribution of Bird Species in British Columbia",
       color = "Species")
```

```{r}
ggplot(data = bird_albers, aes(x = species, weight = individualCount, fill = iucnRedListCategory)) +
  geom_bar() +
  labs(title = "Total Number of Individual Birds Observed by Species",
       x = "Species",
       y = "Total Number of Individuals") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

# ppp Object
```{r}
bird_ppp <- ppp(x = st_coordinates(bird_albers)[, 1], 
                y = st_coordinates(bird_albers)[, 2],
                window = as.owin(window),
                marks = as.factor(bird_albers$iucnRedListCategory))
plot(bird_ppp, cols = rainbow(length(unique(bird_ppp$marks))))
```

## Spatially inhomogeneous $\lambda$
```{r}
Q <- quadratcount(bird_ppp,
                  nx = 5,
                  ny = 5)

plot(bird_ppp,
     pch = 16,
     cex = 0.5,
     cols = "#046C9A")

plot(Q, cex = 1.2, col = "red", add = T)
```

## Intensity
```{r}
plot(intensity(Q, image = T),
     main = "Birds intensity")

plot(bird_ppp,
     pch = 16,
     cex = 0.6,
     cols = "white",
     add = T)

plot(bird_ppp,
     pch = 16,
     cex = 0.5,
     cols = "black",
     add = T)
```

```{r}
quadrat.test(Q)
```

The small p-value suggests that there is a significant deviation from homogeneity.

## Kernel estimation
```{r}
#Density estimation of lambda(u)
lambda_u_hat <- density(bird_ppp)

#Plot the output Note the use of image = TRUE
plot(lambda_u_hat,
     main = "Kernel estimate of Birds intensity")

plot(bird_ppp,
     pch = 16,
     cex = 0.6,
     cols = "white",
     add = T)

plot(bird_ppp,
     pch = 16,
     cex = 0.5,
     cols = "black",
     add = T)
```

## Hot spot analysis
```{r}
# Estimate R
R <- bw.ppl(bird_ppp)
#Calculate test statistic
LR <- scanLRTS(bird_ppp, r = R)

plot(LR)
```

```{r}
#Compute local p-values
pvals <- eval.im(pchisq(LR,
                        df = 1,
                        lower.tail = FALSE))

plot(pvals, main = "Local p-values")
```

## Relationships with covariates
```{r}
bird <- ppp(x = st_coordinates(bird_albers)[, 1], 
                y = st_coordinates(bird_albers)[, 2],
                window = as.owin(window))
elev <- DATA$Elevation
forest <- DATA$Forest
hfi <- DATA$HFI
water <- DATA$Dist_Water
rho_elev <- rhohat(bird, elev)
rho_forest <- rhohat(bird, forest)
rho_hfi <- rhohat(bird, hfi)
rho_water <- rhohat(bird, water)
```

```{r}
par(mfrow = c(2,2))
plot(rho_elev, xlim=c(0, max(rho_elev$elev)),
     main = "",
     xlab = "Elevation (m)")
plot(rho_forest,
     main = "",
     xlab = "Forest Cover (percentage)")
plot(rho_hfi,
     main = "",
     xlab = "HFI")
plot(rho_water,
     main = "",
     xlab = "Water distribution")
```

# K-function
```{r}
E_bird <- envelope(bird,
                  Kest,
                  correction="border",
                  rank = 1,
                  nsim = 19,
                  fix.n = T)
plot(E_bird,
     main = "",
     lwd = 2)
```

## PCF
```{r}
rm(DATA)
rm(bird_data)
rm(bird_ppp)
gc()
```

```{r}
pcf_bird_hom <- envelope(bird,
                          pcf,
                          simulate = expression(rpoispp(density.ppp(bird))),
                          rank = 1,
                          nsim = 19)
pcf_bird_inhom <- envelope(bird,
                          pcfinhom,
                          simulate = expression(rpoispp(density.ppp(bird))),
                          rank = 1,
                          nsim = 19)
par(mfrow = c(1,2))
plot(pcf_bird_hom, main = 'homogeneous pcf')
plot(pcf_bird_inhom,  main = 'inhomogeneous pcf')
```

## Collinearity
```{r}
cor.im(elev, forest, hfi, water, use = 'complete.obs')
```

## Model fitting
```{r}
fit <- ppm(bird, ~ hfi + I(hfi^2) + forest + I(forest^2) + I(hfi*forest))
fit
plot(fit,
     se = FALSE,
     superimpose = FALSE)

plot(bird,
     pch = 16,
     cex = 0.3,
     cols = "green",
     add = TRUE)
```

```{r}
fit <- ppm(bird, ~ forest, Poisson())
fit
plot(fit,
     se = FALSE,
     superimpose = FALSE)

plot(bird,
     pch = 16,
     cex = 0.3,
     cols = "green",
     add = TRUE)
```


